#!/bin/bash
echo ""
echo "BinomialOption"
build/bin/BinomialOption -q -e -t -x 1000 -i 50 "$@"
echo ""
echo "BinomialOptionSimple"
build/bin/BinomialOptionSimple -q -e -t -x 1000 -i 50 "$@"
echo ""
echo "BlackScholes"
build/bin/BlackScholes -q -e -t -x 16384 -i 50 "$@"
echo ""
echo "BlackScholesSimple"
build/bin/BlackScholesSimple -q -e -t -x 16384 -i 50 "$@"
echo ""
echo "BitonicSort"
build/bin/BitonicSort -q -e -x 131072 -t -i 50 "$@"
echo ""
echo "DCT"
build/bin/DCT -q -e -t -x 8192 -y 8192 -i 5 "$@"
echo ""
echo "DwtHaar1D"
build/bin/DwtHaar1D -q -e -t -x 1000000 -i 50 "$@"
echo ""
echo "EigenValue"
build/bin/EigenValue -q -e -t -x 4096 -i 50 "$@"
echo ""
echo "FastWalshTransform"
build/bin/FastWalshTransform -q -e -t -x 1000000 -i 50 "$@"
echo ""
echo "FloydWarshall"
build/bin/FloydWarshall -q -e -t -x 512 -i 50 "$@"
echo ""
echo "Histogram"
build/bin/Histogram -q -e -t -x 8192 -y 8192 -i 50 "$@"
echo ""
echo "Mandelbrot"
build/bin/Mandelbrot -q -e -t -x 4096 -i 5 "$@"
echo ""
echo "MandelbrotSimple"
build/bin/MandelbrotSimple -q -e -t -x 4096 -i 5 "$@"
echo ""
echo "NBody"
build/bin/NBody -q -e -t -x 4096 -i 50 "$@"
echo ""
echo "NBodySimple"
build/bin/NBodySimple -q -e -t -x 4096 -i 50 "$@"
echo ""
echo "MatrixTranspose"
build/bin/MatrixTranspose -q -e -t -x 10000 -i 20 "$@"
echo ""
echo "PrefixSum"
build/bin/PrefixSum -q -e -t -x 16384 -i 1000 "$@"
echo ""
echo "RadixSort"
build/bin/RadixSort -q -e -t -x 1000000 -i 50 "$@"
echo ""
echo "Reduction"
build/bin/Reduction -q -e -t -x 100000 -i 50 "$@"
echo ""
echo "SimpleConvolution"
build/bin/SimpleConvolution -q -e -t -x 1024 -y 1024 -m 1 -i 50 "$@"

# EigenValue fails for size > 4096 (also with ATI's own implementation!)
# PrefixSum fails for larger sizes when using more than one iteration
# PrefixSum uses a maximum of  size 2048 in ATI's implementation
